### ISSUE TITLE
Installation failed on DS715 using DSM 5592

### ISSUE THREAD

**Issue by Letreguilly** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#1]
HI,

I have got an issue on this great package.

When i try to install the package, it can not launch.

I've finally workarround the problem : 
Inside launcher.sh, i'have remove the RAM detection
    tail -n 0 -f /tmp/stdin.${DAEMON_USER} | java -Xmx1G -Xms1G ${JAVA_OPTS} -jar ${JAR_FILE} nogui

The first time I run the server as ROOT, then I changed minecraft folder owner's to minecraft user.

I noticed that minecraft daemon can not access to the /tmp/stdin.minecraft file.

The package is now working correctly

Best regards

**Comment by colin1497** [comment]
OK, I've been occupied but I'll see if I can take a look at it.  DS715 has 2GB of RAM, which is the same as my RS814+, so I wouldn't have expected any issues.

**Comment by colin1497** [comment]
Do you know what output you were getting from the ram detection?  It's just grepping total memory from a free command, so I would think you would end up with exactly the same result from the detection as I have.  Interestingly, I see this:

echo  $((`free | grep Mem: | sed -e "s/^ *Mem: *\([0-9]*\).*$/\1/"`/1024))
1997

(free reports 2045192 total)

You might verify that you get something similar.  After that, it's setting my initial and max heap size to 1792

```
elif [ $RAM -le 2048 ]; then
  JAVA_MAX_HEAP=1792M
```

For some reason, assuming you've got similar results, it sounds like maybe java on your machine isn't liking 1792.  Instead of disabling it completely, you might try to figure out why java isn't accepting this?  Or maybe reducing from 1792 to a lower value like 1536?

Edit: would help if I looked at what you typed.  You had to drop all the way down to 1 gig?  Crazy that you had to go that much lower.  Did you try other values?

**Comment by colin1497** [comment]
Also, I assume that the permissions are a separate issue.  If you could explain what you're seeing in #2

**Comment by Letreguilly** [comment]
when i try the free command :
BusyBox v1.16.1 (2015-06-29 18:12:24 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

serveur> echo $((free | grep Mem: | sed -e "s/^ _Mem:
*([0-9]_)._$/\1/"/1024))
-ash: syntax error: free | grep Mem: | sed -e "s/^ *Mem:
*([0-9]_)._$/1/"/1024
serveur> echo $((free | grep Mem: | sed -e "s/^ *Mem:
*([0-9]_)._$/\1/"/1024))
-ash: syntax error: free | grep Mem: | sed -e "s/^ *Mem:
*([0-9]_)._$/1/"/1024
serveur> free
              total         used         free       shared      buffers
  Mem:      2086304      1736960       349344            0       107328
 Swap:      3350304         4224      3346080
Total:      5436608      1741184      3695424
serveur> free | grep Mem: | sed -e "s/^ *Mem: *([0-9]_).*$/\1/"/1024
sed: bad option in substitution expression
serveur>

2015-08-15 19:26 GMT+02:00 colin1497 notifications@github.com:

**Comment by colin1497** [comment]
In latest version I reduced RAM limits marginally.  If you update, you might let me know if this works for you without manually reducing RAM further.
